AllCops:
  DisplayStyleGuide: true
  DisplayCopNames: true

Layout/DotPosition:
  EnforcedStyle: trailing

Lint/HandleExceptions:
  Exclude:
    - Rakefile

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Metrics/MethodLength:
  Exclude:
    - lib/screen.rb

Style/BlockComments:
  Exclude:
    - spec/spec_helper.rb

Style/Documentation:
  Enabled: false

Style/WordArray:
  Exclude:
    - spec/board_spec.rb # the examples look better with 'X' and nil aligned
